version: '2'

volumes:
  dbdata:
  dbconfig:
  appdb:
  assets:
  distassets:
  extras:

networks:
  backend:

services:
  app:
    image: ghcr.io/agnaistic/agnaistic:latest
    restart: always
    build:
      context: .
    hostname: app
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=agnai
      - INITIAL_USER=admin
      - INITIAL_PASSWORD=password
      - JWT_SECRET=self-hosting
    volumes:
      - appdb:/app/db
      - assets:/app/assets
      - distassets:/app/dist/assets
      - extras:/app/extras
    networks:
      - backend

  mongo:
    image: mongo:8
    restart: always
    volumes:
      - dbdata:/data/db
      - dbconfig:/data/configdb
    networks:
      - backend

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiMzJlZDRjY2E4MWJmYzRlZWZjNGY1NWE0N2RlYjRjMDMiLCJ0IjoiNzc5ZjRjZDUtNDE1Zi00NjFlLWJlOTAtNmQxM2FlZDk4MzNmIiwicyI6Ik5tRXdaalptTUdZdFpHVmtOUzAwTURoaExXSXlPRGt0WldZNE1tSXlZamMwTlRCaiJ9
    networks:
      - backend
